### ISSUE TITLE
같은 값이 연속인 경우

### ISSUE THREAD

**Issue by jeemyeong** [youknowone/codejam2019#1]
https://github.com/youknowone/codejam2019/blob/d6bd391a8e245096209f783b6de81a7f43d12d5c/qc/c.py#L38

같은 값이 연속인 경우에 gcd를 구하면 안되는 것 같아요@_@..

다른 값이 나오는 피벗을 찾아 gcd를 구하고, 그 값으로 나머지 영역을 구하면 될 것 같습니다~!

덕분에 좋은 코드 잘 구경하고 갑니다@_@!! :smile:

**Comment by youknowone** [comment]
감사합니다 왜 안돌아가나 궁금했는데 그게 답인거 같네요
